-- basic syntax
select * from customers;

-- using projection
select firstname, lastname, city from customers;

-- using concatenation and column aliases
select 
	firstname || ' ' || lastname as "Customer Name",
	email as Email_Address
from customers;

-- using SELECT with only expressions
SELECT 123*456 AS RESULT;
SELECT CURRENT_TIMESTAMP;

SELECT 1234*23 AS RESULT, CURRENT_TIMESTAMP;


SELECT * FROM CUSTOMERS;

UPDATE CUSTOMERS SET FIRSTNAME='Aston' WHERE ID=4;


SELECT * FROM CUSTOMERS ORDER BY GENDER DESC;

SELECT * FROM CUSTOMERS ORDER BY GENDER DESC, FIRSTNAME ASC, LASTNAME;

SELECT STATE, GENDER, COUNT(*) FROM CUSTOMERS 
GROUP BY STATE,GENDER ORDER BY STATE, GENDER, COUNT(*) DESC;

SELECT FIRSTNAME, LASTNAME, GENDER, STATE FROM CUSTOMERS ORDER BY STATE, GENDER, FIRSTNAME;

SELECT FIRSTNAME, LASTNAME, STATE FROM CUSTOMERS
ORDER BY STATE DESC NULLS LAST, FIRSTNAME;

SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME
FROM CUSTOMERS
ORDER BY FULLNAME DESC;

SELECT FIRSTNAME || ' ' || LASTNAME AS "CUSTOMER-NAME"
FROM CUSTOMERS
ORDER BY "CUSTOMER-NAME" DESC;

SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME, LENGTH(FIRSTNAME || ' ' || LASTNAME) AS NAME_LENGTH
FROM CUSTOMERS
ORDER BY LENGTH(FIRSTNAME || ' ' || LASTNAME) DESC;

SELECT DISTINCT GENDER FROM CUSTOMERS;
SELECT DISTINCT GENDER, FIRSTNAME FROM CUSTOMERS;
SELECT DISTINCT STATE FROM CUSTOMERS;

SELECT COUNT(DISTINCT STATE) AS NUMBER_OF_STATES FROM CUSTOMERS;

SELECT DISTINCT ON(GENDER) GENDER, ID, FIRSTNAME, LASTNAME FROM CUSTOMERS ORDER BY GENDER, id;


SELECT * FROM CUSTOMERS ORDER BY ID LIMIT 5;
SELECT * FROM CUSTOMERS ORDER BY ID LIMIT 5 OFFSET 10;

-- 7TH PAGE DATA, WHERE IN EACH PAGE HAS 10 RECORDS
SELECT * FROM CUSTOMERS ORDER BY ID LIMIT 10 OFFSET (7-1)*10



SELECT * FROM CUSTOMERS
ORDER BY ID
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM CUSTOMERS FETCH FIRST ROW ONLY;

SELECT * FROM CUSTOMERS ORDER BY ID
OFFSET (7-1)*20
FETCH NEXT 20 ROWS ONLY;



